#include <stdio.h>
void calcDiffInnerElements(int list[][3], int l);
int main ( int argc, char argv[]) 
{
				int a[][3] = {{1,2,3},{4,5,4}};
				calcDiffInnerElements(a,2);
				return 1;
}
void calcDiffInnerElements(int list[][3], int l)
{
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				// Burro;
				for ( int i = 0 ; i < l; i ++ )
								for (int j = 0 ; j < 3 ; j ++)
												printf("%i ", list[i][j]);
}
